// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD98Gbs0hOijCn_KdYHA0hzLiyVtGX1Byw',
    appId: '1:10232607140:web:b2d23169d00cccbf0d9131',
    messagingSenderId: '10232607140',
    projectId: 'glova-mobile-app',
    authDomain: 'glova-mobile-app.firebaseapp.com',
    storageBucket: 'glova-mobile-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOA1y8ult4wcxD1jfwNmfl0CAxLTW348o',
    appId: '1:10232607140:android:8dd87dd4cefc8f1d0d9131',
    messagingSenderId: '10232607140',
    projectId: 'glova-mobile-app',
    storageBucket: 'glova-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuG7XgkXTjOig4_LBsV7472AtLC-7W2dQ',
    appId: '1:10232607140:ios:01c3ac38012b07df0d9131',
    messagingSenderId: '10232607140',
    projectId: 'glova-mobile-app',
    storageBucket: 'glova-mobile-app.appspot.com',
    iosClientId: '10232607140-0n3tm0u91b9089ctme5maidov60u5c80.apps.googleusercontent.com',
    iosBundleId: 'Zyndicate.team.glova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuG7XgkXTjOig4_LBsV7472AtLC-7W2dQ',
    appId: '1:10232607140:ios:c5cb0eb3536a9fe40d9131',
    messagingSenderId: '10232607140',
    projectId: 'glova-mobile-app',
    storageBucket: 'glova-mobile-app.appspot.com',
    iosClientId: '10232607140-ojl5jlmm32g4taanqebdqta9abvocjmc.apps.googleusercontent.com',
    iosBundleId: 'Zyndicate.team.glova.RunnerTests',
  );
}
